spring:
  application:
    name: user-service
  profiles:
    active: dev

  cloud:
    config:
      profile: native
      uri: http://localhost:8888
      fail-fast: true

server:
  port: 8081
  servlet:
    context-path: /api
  error:
    include-stacktrace: never

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /documentation

